### ISSUE TITLE
Build Error: Encountered error: 500 Server Error

### ISSUE THREAD

**Issue by Talderon** [Talderon/k8s-sonarqube#4]
Unexpected error
Encountered error: 500 Server Error: Internal Server Error ("Dockerfile parse error line 60: unknown instruction: GOMETALINGER")
Traceback (most recent call last):
  File "/stage/builder/runner.py", line 288, in _run
    self.build()
  File "/stage/builder/runner.py", line 212, in build
    self._build()
  File "/stage/builder/runner.py", line 200, in _build
    cache_repo)
  File "/stage/builder/build.py", line 43, in build_image
    for line in stream:
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 305, in _stream_helper
    yield self._result(response, json=decode)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 220, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 216, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 30, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("Dockerfile parse error line 60: unknown instruction: GOMETALINGER")

**Comment by Talderon** [comment]
Dockerfile syntax and formatting issues. No longer getting this error.
